/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RH RIFAT
 */
public class Sale_Product_Data extends javax.swing.JFrame {

Connection con=null;
Statement st=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    Connection con2=null;
Statement st2=null;
    PreparedStatement ps2=null;
    ResultSet rs2=null;
    public Sale_Product_Data() {
        initComponents();
        showdata();
    }
    void config(){
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/super_shop", "root", "");
        
    } catch (SQLException ex) {
        
    }
}
    void config2(){
    try {
        con2=DriverManager.getConnection("jdbc:mysql://localhost:3306/super_shop", "root", "");
        
    } catch (SQLException ex) {
        
    }
}
    void clsome(){
        a1.setText("");
    a2.setText("");
    a3.setText("");
    a4.setText("");
    
    }
void cldata(){
    a1.setText("");
    a2.setText("");
    a3.setText("");
    a4.setText("");
    DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
    dt.setRowCount(0);
    showdata();
}
void showdata(){
    try {
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
    dt.setRowCount(0);
        config();
        String ss="SELECT * FROM `super_shop`.`Sales_product2`";
        ps=con.prepareStatement(ss);
        rs=ps.executeQuery();
        while(rs.next()){
            dt.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
        }
    } catch (SQLException ex) {
        Logger.getLogger(Sale_Product_Data.class.getName()).log(Level.SEVERE, null, ex);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        a2 = new javax.swing.JTextField();
        a3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        a4 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sales Product Data");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 0));
        jPanel1.setLayout(null);

        jLabel2.setBackground(new java.awt.Color(0, 0, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sales Product Data");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 1150, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1150, 80);

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Price  :");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(20, 160, 130, 50);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Product ID      :");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 40, 130, 50);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Product Name :");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 100, 130, 50);

        a1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a1KeyTyped(evt);
            }
        });
        jPanel2.add(a1);
        a1.setBounds(150, 40, 320, 50);

        a2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a2KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a2KeyTyped(evt);
            }
        });
        jPanel2.add(a2);
        a2.setBounds(150, 100, 320, 50);

        a3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a3KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a3KeyTyped(evt);
            }
        });
        jPanel2.add(a3);
        a3.setBounds(150, 160, 320, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 0, 153));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Product Price", "Product Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(490, 40, 630, 430);

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setText("Add");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(20, 340, 150, 40);

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Update");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(170, 340, 150, 40);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("Clear");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(90, 380, 150, 40);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Exit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(240, 380, 150, 40);

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton4.setText("Delete");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(320, 340, 150, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Product Details:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 220, 130, 50);

        a4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        a4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                a4KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                a4KeyTyped(evt);
            }
        });
        jPanel2.add(a4);
        a4.setBounds(150, 220, 320, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 80, 1150, 500);

        setSize(new java.awt.Dimension(1160, 616));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO clear
        cldata();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO exit
        int i=JOptionPane.showConfirmDialog(this, "Are you want to exit?","Confirm message",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION){
            dispose();
        }
        else{

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    try {
        // TODO add
        config();
        String id=a1.getText();
        String name=a2.getText();
        String add=a3.getText();
        String det=a4.getText();
        if(a1.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product ID is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a1.requestFocus();
        }
        else if(a2.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product name is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a2.requestFocus();
        }
        else if(a3.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product Price is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a3.requestFocus();
        }
        else if(a4.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product Details is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a4.requestFocus();
        }
        else{
            config2();
            String ss="SELECT * FROM `super_shop`.`Sales_product2` WHERE `Product Id`=?";
            ps2=con2.prepareStatement(ss);
            ps2.setString(1, id);
            rs2=ps2.executeQuery();
            if(rs2.next()){
                JOptionPane.showMessageDialog(this, "Duplicate id ..","Error message",JOptionPane.ERROR_MESSAGE);
                a1.requestFocus();
            }
            else{
        String s="INSERT INTO `super_shop`.`Sales_product2` VALUES(?,?,?,?)";
        ps=con.prepareStatement(s);
        ps.setString(1, id);
        ps.setString(2, name);
        ps.setString(3, add);
        ps.setString(4, det);
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        int p=ps.executeUpdate();
        if(p>0){
            JOptionPane.showMessageDialog(this, "Data add success");
            dt.addRow(new Object[]{id,name,add,det});
            clsome();
        }
        else{
            JOptionPane.showMessageDialog(this, "Data add failed");
        }}}
    } catch (SQLException ex) {
        Logger.getLogger(Sale_Product_Data.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO update
        try {
        config();
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        String id=a1.getText();
        String name=a2.getText();
        String add=a3.getText();
        String det=a4.getText();
        if(a1.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product ID is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a1.requestFocus();
        }
        else if(a2.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product name is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a2.requestFocus();
        }
        else if(a3.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product price is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a3.requestFocus();
        }
        else if(a4.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product details is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a4.requestFocus();
        }
        else{
        String s="UPDATE `super_shop`.`Sales_product2` SET `Product Name` =?,`Product Price` =?,`Product Details`=? WHERE `Product Id` =?";
        ps=con.prepareStatement(s);
        ps.setString(1, name);
        ps.setString(2, add);
        ps.setString(3, det);
        ps.setString(4, ""+dt.getValueAt(jTable1.getSelectedRow(), 0));
        dt.setRowCount(0);
        int p=ps.executeUpdate();
        if(p>0){
            JOptionPane.showMessageDialog(this, "Data update success");
            dt.addRow(new Object[]{id,name,add,det});
            clsome();
        }
        else{
            JOptionPane.showMessageDialog(this, "Data update failed");
        }}
    } catch (SQLException ex) {
        Logger.getLogger(Sale_Product_Data.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void a1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(a1.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product ID is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a1.requestFocus();
           }
           else{
               a2.requestFocus();
           }
       }
    }//GEN-LAST:event_a1KeyPressed

    private void a2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(a2.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product name is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a2.requestFocus();
           }
           else{
               a3.requestFocus();
           }
       }
    }//GEN-LAST:event_a2KeyPressed

    private void a3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyPressed
       if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(a3.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product price is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a3.requestFocus();
           }
           else{
               a4.requestFocus();
           }
       }
    }//GEN-LAST:event_a3KeyPressed

    private void a1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a1KeyTyped
        char ch=evt.getKeyChar();
       if(!(Character.isDigit(ch)) || ch==KeyEvent.VK_ENTER || ch==KeyEvent.VK_BACK_SPACE || ch==KeyEvent.VK_DELETE){
           evt.consume();
       }
    }//GEN-LAST:event_a1KeyTyped

    private void a2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a2KeyTyped
        char ch=evt.getKeyChar();
       if((Character.isDigit(ch)) || ch==KeyEvent.VK_ENTER || ch==KeyEvent.VK_BACK_SPACE || ch==KeyEvent.VK_DELETE){
           evt.consume();
       }
    }//GEN-LAST:event_a2KeyTyped

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        a1.setText(""+dt.getValueAt(jTable1.getSelectedRow(), 0));
        a2.setText(""+dt.getValueAt(jTable1.getSelectedRow(), 1));
        a3.setText(""+dt.getValueAt(jTable1.getSelectedRow(), 2));
        a4.setText(""+dt.getValueAt(jTable1.getSelectedRow(), 3));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO delete
        try {
        config();
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        String id=a1.getText();
        String name=a2.getText();
        String add=a3.getText();
        if(a1.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product ID is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a1.requestFocus();
        }
        else if(a2.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product name is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a2.requestFocus();
        }
        else if(a3.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product Price is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a3.requestFocus();
        }
        else{
        String s="DELETE FROM `super_shop`.`Sales_product2` WHERE `Product Id` =?";
        ps=con.prepareStatement(s);
        ps.setString(1, ""+dt.getValueAt(jTable1.getSelectedRow(), 0));
        dt.setRowCount(0);
        int p=ps.executeUpdate();
        if(p>0){
            JOptionPane.showMessageDialog(this, "Data delete success");
            clsome();
            showdata();
        }
        else{
            JOptionPane.showMessageDialog(this, "Data delete failed");
        }}
    } catch (SQLException ex) {
        Logger.getLogger(Sale_Product_Data.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void a3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a3KeyTyped
        char ch=evt.getKeyChar();
       if(!(Character.isDigit(ch)) || ch==KeyEvent.VK_ENTER || ch==KeyEvent.VK_BACK_SPACE || ch==KeyEvent.VK_DELETE){
           evt.consume();
       }
    }//GEN-LAST:event_a3KeyTyped

    private void a4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a4KeyPressed
         if(evt.getKeyCode()==KeyEvent.VK_ENTER){
           if(a4.getText().isEmpty()){
               JOptionPane.showMessageDialog(this, "Product Details is empty!!","Error message",JOptionPane.ERROR_MESSAGE);
               a4.requestFocus();
           }
           else{
              // a4.requestFocus();
           }
       }
    }//GEN-LAST:event_a4KeyPressed

    private void a4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_a4KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_a4KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sale_Product_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sale_Product_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sale_Product_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sale_Product_Data.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sale_Product_Data().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JTextField a2;
    private javax.swing.JTextField a3;
    private javax.swing.JTextField a4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
