/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package common;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author RH RIFAT
 */
public class StockReport extends javax.swing.JFrame {

Connection con=null;
    PreparedStatement ps=null;
    ResultSet rs=null;
    public StockReport() {
        initComponents();
    }
void config(String s){
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/super_shop", "root", "");
        ps=con.prepareStatement(s);
        rs=ps.executeQuery();
        DefaultTableModel dd=(DefaultTableModel)jTable1.getModel();
        dd.setRowCount(0);
        while(rs.next()){
             dd.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
        }
    } catch (SQLException ex) {
        
    }
}
void config2(String s){
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/super_shop", "root", "");
        ps=con.prepareStatement(s);
        rs=ps.executeQuery();
        int a=0,b=0,c=0,d=0,e=0;
        while(rs.next()){
             a=rs.getInt(2)+a;
              b=rs.getInt(3)+b;
               c=rs.getInt(4)+c;
                d=rs.getInt(5)+d;
                 e=rs.getInt(6)+e;
        }
        s1.setText(""+a);
        s2.setText(""+b);
        s3.setText(""+c);
        s4.setText(""+d);
        s5.setText(""+e);
        s6.setText(""+a);
        s12.setText(""+c);
        s13.setText(""+e);
        s14.setText(""+a);
        int x=c+e;
        s11.setText(""+x);
        
    } catch (SQLException ex) {
        
    }
}
void configTest(String s){
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/super_shop", "root", "");
        ps=con.prepareStatement(s);
        ps.setString(1, a1.getText());
        rs=ps.executeQuery();
        DefaultTableModel dd=(DefaultTableModel)jTable1.getModel();
        dd.setRowCount(0);
        while(rs.next()){
             dd.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4)});
        }
    } catch (SQLException ex) {
        
    }
}
void configTest2(String s){
    try {
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/super_shop", "root", "");
        ps=con.prepareStatement(s);
        ps.setString(1, a1.getText());
        rs=ps.executeQuery();
        int a=0,b=0,c=0,d=0,e=0;
        while(rs.next()){
             a=rs.getInt(2)+a;
              b=rs.getInt(3)+b;
               c=rs.getInt(4)+c;
                d=rs.getInt(5)+d;
                 e=rs.getInt(6)+e;
        }
        s1.setText(""+a);
        s2.setText(""+b);
        s3.setText(""+c);
        s4.setText(""+d);
        s5.setText(""+e);
        s6.setText(""+a);
        s12.setText(""+c);
        s13.setText(""+e);
        s14.setText(""+a);
        int x=c+e;
        s11.setText(""+x);
    } catch (SQLException ex) {
        
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        a1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        s1 = new javax.swing.JTextField();
        s2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        s4 = new javax.swing.JTextField();
        s5 = new javax.swing.JTextField();
        s6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        s11 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        s12 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        s13 = new javax.swing.JTextField();
        s14 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stock Report");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Report");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)));
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 10, 750, 60);

        a1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        a1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(a1);
        a1.setBounds(120, 110, 190, 40);

        jButton1.setBackground(new java.awt.Color(153, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Find All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(450, 110, 110, 40);

        jButton2.setBackground(new java.awt.Color(153, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Find");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(320, 110, 110, 40);

        jButton4.setBackground(new java.awt.Color(153, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(580, 110, 110, 40);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Total Purchase ", "Total Sales", "Stock"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 670, 520);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 0));
        jLabel2.setText("Product Name :");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 110, 100, 40);

        s3.setEditable(false);
        s3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s3.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(s3);
        s3.setBounds(960, 270, 200, 40);

        s1.setEditable(false);
        s1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s1.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(s1);
        s1.setBounds(960, 170, 200, 40);

        s2.setEditable(false);
        s2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s2.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(s2);
        s2.setBounds(960, 220, 200, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Investment                      :");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jPanel1.add(jLabel3);
        jLabel3.setBounds(740, 170, 210, 40);

        s4.setEditable(false);
        s4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s4.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(s4);
        s4.setBounds(960, 320, 200, 40);

        s5.setEditable(false);
        s5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s5.setForeground(new java.awt.Color(153, 0, 0));
        jPanel1.add(s5);
        s5.setBounds(960, 370, 200, 40);

        s6.setEditable(false);
        s6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s6.setForeground(new java.awt.Color(153, 0, 0));
        s6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(s6);
        s6.setBounds(730, 600, 170, 40);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Total sale                        :");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jPanel1.add(jLabel4);
        jLabel4.setBounds(740, 220, 210, 40);

        s11.setEditable(false);
        s11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s11.setForeground(new java.awt.Color(153, 0, 0));
        s11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(s11);
        s11.setBounds(970, 650, 170, 40);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Benifits                            :");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jPanel1.add(jLabel5);
        jLabel5.setBounds(740, 320, 210, 40);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setText("Orginal sales ammount  :");
        jLabel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jPanel1.add(jLabel6);
        jLabel6.setBounds(740, 270, 210, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Assets                              :");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 1, true));
        jPanel1.add(jLabel7);
        jLabel7.setBounds(740, 370, 210, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Assets");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1180, 550, 140, 40);

        s12.setEditable(false);
        s12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s12.setForeground(new java.awt.Color(153, 0, 0));
        s12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        jPanel1.add(s12);
        s12.setBounds(970, 600, 170, 40);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Invest ");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.add(jLabel9);
        jLabel9.setBounds(730, 550, 170, 40);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Orginal salse ammount");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 0)));
        jPanel1.add(jLabel10);
        jLabel10.setBounds(970, 550, 170, 40);

        s13.setEditable(false);
        s13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s13.setForeground(new java.awt.Color(153, 0, 0));
        s13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(s13);
        s13.setBounds(1180, 600, 140, 40);

        s14.setEditable(false);
        s14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        s14.setForeground(new java.awt.Color(153, 0, 0));
        s14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(s14);
        s14.setBounds(730, 650, 170, 40);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(153, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("=");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(910, 650, 50, 40);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(153, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("=");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(910, 550, 50, 40);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(153, 0, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("=");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(910, 600, 50, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(153, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("+");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(1140, 550, 40, 40);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(153, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("+");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1140, 600, 40, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1330, 730);

        setSize(new java.awt.Dimension(1344, 763));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       a1.setText("");
       s1.setText("");
       s2.setText("");
       s3.setText("");
       s4.setText("");
       s5.setText("");
       s6.setText("");
       s11.setText("");
       s12.setText("");
       s13.setText("");
       s14.setText("");
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        config("SELECT * FROM `stock`");
        config2("SELECT * FROM `final`");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DefaultTableModel dt=(DefaultTableModel)jTable1.getModel();
        dt.setRowCount(0);
        configTest("SELECT * FROM `stock` WHERE `Product Name`=?");
        configTest2("SELECT * FROM `final` WHERE `Product Name`=?");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_s12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StockReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StockReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField a1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s11;
    private javax.swing.JTextField s12;
    private javax.swing.JTextField s13;
    private javax.swing.JTextField s14;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    private javax.swing.JTextField s4;
    private javax.swing.JTextField s5;
    private javax.swing.JTextField s6;
    // End of variables declaration//GEN-END:variables
}
